# Generated by Django 5.0.4 on 2024-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
