# Generated by Django 5.0.4 on 2024-04-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(max_length=255, upload_to='uploads/%y'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, upload_to='uploads/%y'),
        ),
    ]
